/* Polen-Camper: Stellplätze, Servicepunkte, Campingplätze & MOPs.
   Aus Justines Camper-Liste. Kategorien: camping/camperservice/entsorgung. */
window.POLEN_CAMPER = [
 {
  "id": "camper-park-gzub-annopole",
  "name": "Camper Park Gzub",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 509.2,
  "y": 407.8,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Gzub%20Annopole%20%20Polska",
  "meta": "Annopole (Środa Wlkp.) · Ganzjährig",
  "blurb": "Stellplatz / Camping in Annopole (Środa Wlkp.). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "flaj-camper-serwis-augustow",
  "name": "FLAJ Camper Serwis",
  "region": "masuren",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 586.4,
  "y": 364.5,
  "url": "https://www.google.com/maps/search/?api=1&query=FLAJ%20Camper%20Serwis%20August%C3%B3w%20Polska",
  "meta": "Augustów · Saisonal",
  "blurb": "Camper-Servicepunkt in Augustów. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "jura-park-ba-tow-ba-tow",
  "name": "Jura Park Bałtów",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 569,
  "y": 433.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Jura%20Park%20Ba%C5%82t%C3%B3w%20Ba%C5%82t%C3%B3w%20Polska",
  "meta": "Bałtów · Ganzjährig",
  "blurb": "Stellplatz / Camping in Bałtów. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanowiska-obs-ugi-kamperow-bartoszyce",
  "name": "Stanowiska obsługi kamperów",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 556.3,
  "y": 357.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanowiska%20obs%C5%82ugi%20kamper%C3%B3w%20Bartoszyce%20Polska",
  "meta": "Bartoszyce · Saisonal",
  "blurb": "Stellplatz / Camping in Bartoszyce. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "estancia-camper-park-bia-a-gora",
  "name": "Estancia Camper Park",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 531.1,
  "y": 372.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Estancia%20Camper%20Park%20Bia%C5%82a%20G%C3%B3ra%20Polska",
  "meta": "Biała Góra · Saisonal",
  "blurb": "Stellplatz / Camping in Biała Góra. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanica-kajakarska-bia-ogard",
  "name": "Stanica kajakarska",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 490.1,
  "y": 368.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanica%20kajakarska%20Bia%C5%82ogard%20Polska",
  "meta": "Białogard · Saisonal",
  "blurb": "Stellplatz / Camping in Białogard. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "nadlesnictwo-choczewo-bia-ogora",
  "name": "Nadleśnictwo Choczewo",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 515.8,
  "y": 347.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Nadle%C5%9Bnictwo%20Choczewo%20Bia%C5%82og%C3%B3ra%20Polska",
  "meta": "Białogóra · Saisonal",
  "blurb": "Stellplatz / Camping in Białogóra. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osiw-dojlidy-bia-ystok",
  "name": "OSiW Dojlidy",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 589.5,
  "y": 380.6,
  "url": "https://www.google.com/maps/search/?api=1&query=OSiW%20Dojlidy%20Bia%C5%82ystok%20Polska",
  "meta": "Białystok · Saisonal",
  "blurb": "Stellplatz / Camping in Białystok. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osir-bielawa-bielawa",
  "name": "OSiR Bielawa",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 501.3,
  "y": 443.9,
  "url": "https://www.google.com/maps/search/?api=1&query=OSiR%20Bielawa%20Bielawa%20Polska",
  "meta": "Bielawa · Saisonal",
  "blurb": "Stellplatz / Camping in Bielawa. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "bielsko-bia-a-camper-park-bielsko-bia-a",
  "name": "Bielsko-Biała Camper Park",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 535.4,
  "y": 461.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Bielsko-Bia%C5%82a%20Camper%20Park%20Bielsko-Bia%C5%82a%20Polska",
  "meta": "Bielsko-Biała · Ganzjährig",
  "blurb": "Stellplatz / Camping in Bielsko-Biała. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "pole-namiotowe-bobiecin",
  "name": "Pole namiotowe",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 500.5,
  "y": 364.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Pole%20namiotowe%20Bobi%C4%99cin%20Polska",
  "meta": "Bobięcin · Saisonal",
  "blurb": "Stellplatz / Camping in Bobięcin. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanowisko-obs-ugi-kamperow-boles-awiec",
  "name": "Stanowisko obsługi kamperów",
  "region": "westen",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 486.5,
  "y": 432,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanowisko%20obs%C5%82ugi%20kamper%C3%B3w%20Boles%C5%82awiec%20Polska",
  "meta": "Bolesławiec · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Bolesławiec. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kampery-borzechowo-borzechowo",
  "name": "Kampery Borzechowo",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 523.6,
  "y": 367.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Kampery%20Borzechowo%20Borzechowo%20Polska",
  "meta": "Borzechowo · Saisonal",
  "blurb": "Stellplatz / Camping in Borzechowo. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "jedwabno-camping-binduga-brajniki",
  "name": "Jedwabno Camping Binduga",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 556,
  "y": 373.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Jedwabno%20Camping%20Binduga%20Brajniki%20%20Polska",
  "meta": "Brajniki (Jez. Świętajno) · Saisonal",
  "blurb": "Stellplatz / Camping in Brajniki (Jez. Świętajno). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "tatrzanski-camper-park-bukowina-tatrzanska",
  "name": "Tatrzański Camper Park",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 550.3,
  "y": 471.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Tatrza%C5%84ski%20Camper%20Park%20Bukowina%20Tatrza%C5%84ska%20Polska",
  "meta": "Bukowina Tatrzańska · Ganzjährig",
  "blurb": "Stellplatz / Camping in Bukowina Tatrzańska. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-szczutki-po-udnie-bydgoszcz",
  "name": "MOP Szczutki Południe",
  "region": "norden",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 518.2,
  "y": 385.7,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Szczutki%20Po%C5%82udnie%20Bydgoszcz%20%20Polska",
  "meta": "Bydgoszcz (S5) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Bydgoszcz (S5). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-szczutki-po-noc-bydgoszcz",
  "name": "MOP Szczutki Północ",
  "region": "norden",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 518.3,
  "y": 385.4,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Szczutki%20P%C3%B3%C5%82noc%20Bydgoszcz%20%20Polska",
  "meta": "Bydgoszcz (S5) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Bydgoszcz (S5). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "inter-nos-kemping-na-wyspie-b-edno",
  "name": "Inter Nos – kemping na wyspie",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 490.1,
  "y": 405.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Inter%20Nos%20%20kemping%20na%20wyspie%20B%C5%82%C4%99dno%20Polska",
  "meta": "Błędno · Saisonal",
  "blurb": "Stellplatz / Camping in Błędno. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stacja-bp-celbowo",
  "name": "Stacja BP",
  "region": "norden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 522.8,
  "y": 350.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Stacja%20BP%20Celbowo%20%20Polska",
  "meta": "Celbowo (k. Puck) · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Celbowo (k. Puck). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-alexa-ch-apowo",
  "name": "Camping Alexa",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 522.4,
  "y": 347.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20Alexa%20Ch%C5%82apowo%20Polska",
  "meta": "Chłapowo · Ganzjährig",
  "blurb": "Stellplatz / Camping in Chłapowo. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "horyzont-camp-ch-apowo",
  "name": "Horyzont Camp",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 522.7,
  "y": 347.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Horyzont%20Camp%20Ch%C5%82apowo%20Polska",
  "meta": "Chłapowo · Ganzjährig",
  "blurb": "Stellplatz / Camping in Chłapowo. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-pa-ac-nad-jeziorem-chociwel",
  "name": "Camper Park Pałac Nad Jeziorem",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 481.7,
  "y": 381.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Pa%C5%82ac%20Nad%20Jeziorem%20Chociwel%20Polska",
  "meta": "Chociwel · Saisonal",
  "blurb": "Stellplatz / Camping in Chociwel. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "zatoka-zab-ockich-chomiaza-ksieza",
  "name": "Zatoka Zabłockich",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 516,
  "y": 394.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Zatoka%20Zab%C5%82ockich%20Chomi%C4%85%C5%BCa%20Ksi%C4%99%C5%BCa%20Polska",
  "meta": "Chomiąża Księża · Saisonal",
  "blurb": "Stellplatz / Camping in Chomiąża Księża. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-nr-80-cz-uchow",
  "name": "Camping nr 80",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 509.3,
  "y": 374.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20nr%2080%20Cz%C5%82uch%C3%B3w%20Polska",
  "meta": "Człuchów · Saisonal",
  "blurb": "Stellplatz / Camping in Człuchów. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "samoobs-ugowy-parking-przy-plazy-dar-owko-wschodnie",
  "name": "Samoobsługowy parking przy plaży",
  "region": "norden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 495.6,
  "y": 358.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Samoobs%C5%82ugowy%20parking%20przy%20pla%C5%BCy%20Dar%C5%82%C3%B3wko%20Wschodnie%20Polska",
  "meta": "Darłówko Wschodnie · Saisonal",
  "blurb": "Camper-Servicepunkt in Darłówko Wschodnie. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "sta-y-lad-dar-owko-zachodnie",
  "name": "Stały Ląd",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 494.9,
  "y": 358.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Sta%C5%82y%20L%C4%85d%20Dar%C5%82%C3%B3wko%20Zachodnie%20Polska",
  "meta": "Darłówko Zachodnie · Ganzjährig",
  "blurb": "Stellplatz / Camping in Darłówko Zachodnie. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "drohiczyn-camper-stop-drohiczyn",
  "name": "Drohiczyn Camper Stop",
  "region": "masuren",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 583.1,
  "y": 397.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Drohiczyn%20Camper%20Stop%20Drohiczyn%20Polska",
  "meta": "Drohiczyn · Saisonal",
  "blurb": "Camper-Servicepunkt in Drohiczyn. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-herbergerowka-duszniki-zdroj",
  "name": "Camper Park Herbergerówka",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 498.3,
  "y": 450.8,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Herberger%C3%B3wka%20Duszniki-Zdr%C3%B3j%20Polska",
  "meta": "Duszniki-Zdrój · Saisonal",
  "blurb": "Stellplatz / Camping in Duszniki-Zdrój. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "na-wydmie-apartments-camp-dziwnowek",
  "name": "Na Wydmie Apartments & Camp",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 473.5,
  "y": 369.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Na%20Wydmie%20Apartments%20%26%20Camp%20Dziwn%C3%B3wek%20Polska",
  "meta": "Dziwnówek · Ganzjährig",
  "blurb": "Stellplatz / Camping in Dziwnówek. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-black-pearl-dziwnow",
  "name": "Camping Black Pearl",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 473.1,
  "y": 369.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20Black%20Pearl%20Dziwn%C3%B3w%20Polska",
  "meta": "Dziwnów · Saisonal",
  "blurb": "Stellplatz / Camping in Dziwnów. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanowisko-obs-ugi-kamperow-folusz",
  "name": "Stanowisko obsługi kamperów",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 569.3,
  "y": 462.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanowisko%20obs%C5%82ugi%20kamper%C3%B3w%20Folusz%20%20Polska",
  "meta": "Folusz (Jasło) · Saisonal",
  "blurb": "Camper-Servicepunkt in Folusz (Jasło). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "green-velo-camp-gawrych-ruda",
  "name": "Green Velo Camp",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 586.6,
  "y": 360.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Green%20Velo%20Camp%20Gawrych-Ruda%20Polska",
  "meta": "Gawrych-Ruda · Saisonal",
  "blurb": "Stellplatz / Camping in Gawrych-Ruda. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-giebu-tow-giebu-tow",
  "name": "MOP Giebułtów",
  "region": "sueden",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 546.9,
  "y": 452.6,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Giebu%C5%82t%C3%B3w%20Giebu%C5%82t%C3%B3w%20%20Polska",
  "meta": "Giebułtów (S7) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Giebułtów (S7). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kemping-stawy-marcowe-g-uszyca",
  "name": "Kemping Stawy Marcowe",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 497.8,
  "y": 444.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Kemping%20Stawy%20Marcowe%20G%C5%82uszyca%20Polska",
  "meta": "Głuszyca · Saisonal",
  "blurb": "Stellplatz / Camping in Głuszyca. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "parking-miejski-ladestation-gocza-kowice-zdroj",
  "name": "Parking miejski (Ladestation)",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 534,
  "y": 458.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Parking%20miejski%20(Ladestation)%20Gocza%C5%82kowice-Zdr%C3%B3j%20Polska",
  "meta": "Goczałkowice-Zdrój · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Goczałkowice-Zdrój. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "gotis-go-uchow",
  "name": "GOTiS",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 518.5,
  "y": 415.5,
  "url": "https://www.google.com/maps/search/?api=1&query=GOTiS%20Go%C5%82uch%C3%B3w%20Polska",
  "meta": "Gołuchów · Saisonal",
  "blurb": "Stellplatz / Camping in Gołuchów. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "bajka-hotel-resort-grodziec",
  "name": "Bajka Hotel & Resort",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 519.4,
  "y": 414.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Bajka%20Hotel%20%26%20Resort%20Grodziec%20Polska",
  "meta": "Grodziec · Saisonal",
  "blurb": "Stellplatz / Camping in Grodziec. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kaszuby-camper-stop-grzybno",
  "name": "Kaszuby Camper Stop",
  "region": "norden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 518.9,
  "y": 359.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Kaszuby%20Camper%20Stop%20Grzybno%20%20Polska",
  "meta": "Grzybno (k. Kartuzy) · Saisonal",
  "blurb": "Camper-Servicepunkt in Grzybno (k. Kartuzy). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "lubie-resort-camper-park-gudowo",
  "name": "Lubie Resort Camper Park",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 488.6,
  "y": 379.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Lubie%20Resort%20Camper%20Park%20Gudowo%20Polska",
  "meta": "Gudowo · Saisonal",
  "blurb": "Stellplatz / Camping in Gudowo. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "winnica-sandomierska-camp-gory-wysokie",
  "name": "Winnica Sandomierska Camp",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 571.5,
  "y": 437.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Winnica%20Sandomierska%20Camp%20G%C3%B3ry%20Wysokie%20Polska",
  "meta": "Góry Wysokie · Saisonal",
  "blurb": "Stellplatz / Camping in Góry Wysokie. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-kalina-nr-178-jantar",
  "name": "Camping Kalina nr 178",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 532.7,
  "y": 357.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20Kalina%20nr%20178%20Jantar%20Polska",
  "meta": "Jantar · Saisonal",
  "blurb": "Stellplatz / Camping in Jantar. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "parking-jasnej-gory-czestochowa",
  "name": "Parking Jasnej Góry",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 535.4,
  "y": 438.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Parking%20Jasnej%20G%C3%B3ry%20Cz%C4%99stochowa%20%20Polska",
  "meta": "Częstochowa (Jasna Góra) · Saisonal",
  "blurb": "Camper-Servicepunkt in Częstochowa (Jasna Góra). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-nad-sosina-jaworzno",
  "name": "Camper Park nad Sosiną",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 538.2,
  "y": 452.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20nad%20Sosin%C4%85%20Jaworzno%20Polska",
  "meta": "Jaworzno · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Jaworzno. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "hotel-camping-jazy-jazy",
  "name": "Hotel Camping Jazy",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 544.2,
  "y": 462.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Hotel%20Camping%20Jazy%20Jazy%20%20Polska",
  "meta": "Jazy (Maków Podh.) · Saisonal",
  "blurb": "Stellplatz / Camping in Jazy (Maków Podh.). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stacja-paliw-circle-k-jedrzychowice",
  "name": "Stacja Paliw Circle K",
  "region": "westen",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 479,
  "y": 434.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Stacja%20Paliw%20Circle%20K%20J%C4%99drzychowice%20%20Polska",
  "meta": "Jędrzychowice (A4) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Jędrzychowice (A4). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-kalisz-kalisz",
  "name": "Camper Park Kalisz",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 520.7,
  "y": 417.7,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Kalisz%20Kalisz%20Polska",
  "meta": "Kalisz · Ganzjährig",
  "blurb": "Stellplatz / Camping in Kalisz. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "marina-kamien-pomorski-kamien-pomorski",
  "name": "Marina Kamień Pomorski",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 473.4,
  "y": 370.7,
  "url": "https://www.google.com/maps/search/?api=1&query=Marina%20Kamie%C5%84%20Pomorski%20Kamie%C5%84%20Pomorski%20Polska",
  "meta": "Kamień Pomorski · Saisonal",
  "blurb": "Stellplatz / Camping in Kamień Pomorski. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "zbiornik-wodny-w-kaniowie-kaniow",
  "name": "Zbiornik wodny w Kaniowie",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 556.1,
  "y": 432.7,
  "url": "https://www.google.com/maps/search/?api=1&query=Zbiornik%20wodny%20w%20Kaniowie%20Kani%C3%B3w%20%20Polska",
  "meta": "Kaniów (Zagnańsk) · Saisonal",
  "blurb": "Camper-Servicepunkt in Kaniów (Zagnańsk). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-kochlice-wschod-kochlice",
  "name": "MOP Kochlice Wschód",
  "region": "westen",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 492.1,
  "y": 431,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Kochlice%20Wsch%C3%B3d%20Kochlice%20%20Polska",
  "meta": "Kochlice (S3) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Kochlice (S3). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-kochlice-zachod-kochlice",
  "name": "MOP Kochlice Zachód",
  "region": "westen",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 492.4,
  "y": 431,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Kochlice%20Zach%C3%B3d%20Kochlice%20%20Polska",
  "meta": "Kochlice (S3) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Kochlice (S3). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-baltic-ko-obrzeg",
  "name": "Camping Baltic",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 484.4,
  "y": 364.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20Baltic%20Ko%C5%82obrzeg%20Polska",
  "meta": "Kołobrzeg · Ganzjährig",
  "blurb": "Stellplatz / Camping in Kołobrzeg. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kampery-ko-obrzeg-ko-obrzeg",
  "name": "Kampery Kołobrzeg",
  "region": "norden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 484.2,
  "y": 364.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Kampery%20Ko%C5%82obrzeg%20Ko%C5%82obrzeg%20Polska",
  "meta": "Kołobrzeg · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Kołobrzeg. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "wawawake-camper-park-konstancin-jeziorna",
  "name": "WawaWake Camper Park",
  "region": "zentral",
  "kat": "camping",
  "status": "sehenswert",
  "x": 562,
  "y": 406.7,
  "url": "https://www.google.com/maps/search/?api=1&query=WawaWake%20Camper%20Park%20Konstancin-Jeziorna%20Polska",
  "meta": "Konstancin-Jeziorna · Saisonal",
  "blurb": "Stellplatz / Camping in Konstancin-Jeziorna. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "fly-resort-kopan-kopan",
  "name": "Fly Resort Kopań",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 493.1,
  "y": 357.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Fly%20Resort%20Kopa%C5%84%20Kopa%C5%84%20Polska",
  "meta": "Kopań · Saisonal",
  "blurb": "Stellplatz / Camping in Kopań. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osir-kozienice-kozienice",
  "name": "OSiR Kozienice",
  "region": "zentral",
  "kat": "camping",
  "status": "sehenswert",
  "x": 568.5,
  "y": 417.9,
  "url": "https://www.google.com/maps/search/?api=1&query=OSiR%20Kozienice%20Kozienice%20Polska",
  "meta": "Kozienice · Saisonal",
  "blurb": "Stellplatz / Camping in Kozienice. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kapielisko-gminne-w-kozielsku-kozielsko",
  "name": "Kąpielisko Gminne w Kozielsku",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 528.9,
  "y": 442.3,
  "url": "https://www.google.com/maps/search/?api=1&query=K%C4%85pielisko%20Gminne%20w%20Kozielsku%20Kozielsko%20Polska",
  "meta": "Kozielsko · Saisonal",
  "blurb": "Camper-Servicepunkt in Kozielsko. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "krasiejow-jura-park-krasiejow",
  "name": "Krasiejów Jura Park",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 524.1,
  "y": 442.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Krasiej%C3%B3w%20Jura%20Park%20Krasiej%C3%B3w%20Polska",
  "meta": "Krasiejów · Ganzjährig",
  "blurb": "Stellplatz / Camping in Krasiejów. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "przystan-narie-kretowiny",
  "name": "Przystań Narie",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 544.7,
  "y": 367.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Przysta%C5%84%20Narie%20Kretowiny%20Polska",
  "meta": "Kretowiny · Ganzjährig",
  "blurb": "Stellplatz / Camping in Kretowiny. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-bursaki-krosno",
  "name": "Camper Park Bursaki",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 572.9,
  "y": 461.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Bursaki%20Krosno%20%20Polska",
  "meta": "Krosno (MOSiR) · Saisonal",
  "blurb": "Stellplatz / Camping in Krosno (MOSiR). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "zamek-podewils-krag",
  "name": "Zamek Podewils",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 500.5,
  "y": 363.2,
  "url": "https://www.google.com/maps/search/?api=1&query=Zamek%20Podewils%20Kr%C4%85g%20Polska",
  "meta": "Krąg · Saisonal",
  "blurb": "Stellplatz / Camping in Krąg. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kamperowa-kudowa-kudowa-zdroj",
  "name": "Kamperowa Kudowa",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 496.3,
  "y": 450,
  "url": "https://www.google.com/maps/search/?api=1&query=Kamperowa%20Kudowa%20Kudowa-Zdr%C3%B3j%20Polska",
  "meta": "Kudowa-Zdrój · Ganzjährig",
  "blurb": "Stellplatz / Camping in Kudowa-Zdrój. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-kudowa-kudowa-zdroj",
  "name": "Camper Park Kudowa",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 496.6,
  "y": 450,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Kudowa%20Kudowa-Zdr%C3%B3j%20Polska",
  "meta": "Kudowa-Zdrój · Ganzjährig",
  "blurb": "Stellplatz / Camping in Kudowa-Zdrój. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kite-parking-kuznica",
  "name": "Kite Parking",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 524.8,
  "y": 349.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Kite%20Parking%20Ku%C5%BAnica%20%20Polska",
  "meta": "Kuźnica (Płw. Helski) · Ganzjährig",
  "blurb": "Stellplatz / Camping in Kuźnica (Płw. Helski). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "pa-ac-lasow-lasow",
  "name": "Pałac Lasów",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 477.9,
  "y": 432.2,
  "url": "https://www.google.com/maps/search/?api=1&query=Pa%C5%82ac%20Las%C3%B3w%20Las%C3%B3w%20%20Polska",
  "meta": "Lasów (k. Zgorzelec) · Saisonal",
  "blurb": "Stellplatz / Camping in Lasów (k. Zgorzelec). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-234-legnickie-pole",
  "name": "Camping 234",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 496.3,
  "y": 433.7,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20234%20Legnickie%20Pole%20Polska",
  "meta": "Legnickie Pole · Ganzjährig",
  "blurb": "Stellplatz / Camping in Legnickie Pole. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "ow-zag-ebocze-lejno",
  "name": "OW Zagłębocze",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 588.6,
  "y": 420.4,
  "url": "https://www.google.com/maps/search/?api=1&query=OW%20Zag%C5%82%C4%99bocze%20Lejno%20Polska",
  "meta": "Lejno · Saisonal",
  "blurb": "Stellplatz / Camping in Lejno. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanowisko-obs-ugi-kamperow-lidzbark-warminski",
  "name": "Stanowisko obsługi kamperów",
  "region": "masuren",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 553.2,
  "y": 360.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanowisko%20obs%C5%82ugi%20kamper%C3%B3w%20Lidzbark%20Warmi%C5%84ski%20Polska",
  "meta": "Lidzbark Warmiński · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Lidzbark Warmiński. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "jezowa-woda-palmiarnia-spa-limanowa",
  "name": "Jeżowa Woda – palmiarnia & spa",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 555.1,
  "y": 462.7,
  "url": "https://www.google.com/maps/search/?api=1&query=Je%C5%BCowa%20Woda%20%20palmiarnia%20%26%20spa%20Limanowa%20%20Polska",
  "meta": "Limanowa (Przyszowa) · Saisonal",
  "blurb": "Stellplatz / Camping in Limanowa (Przyszowa). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osrodek-taurus-linowno",
  "name": "Ośrodek Taurus",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 481.2,
  "y": 385.4,
  "url": "https://www.google.com/maps/search/?api=1&query=O%C5%9Brodek%20Taurus%20Linowno%20Polska",
  "meta": "Linowno · Saisonal",
  "blurb": "Stellplatz / Camping in Linowno. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "pole-biwakowe-przy-zamku-liw",
  "name": "Pole biwakowe przy Zamku",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 574,
  "y": 398.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Pole%20biwakowe%20przy%20Zamku%20Liw%20%20Polska",
  "meta": "Liw (Węgrów) · Saisonal",
  "blurb": "Stellplatz / Camping in Liw (Węgrów). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "circle-k-a1-mop-lubien-po-udnie-lubien-kujawski",
  "name": "Circle-K A1 (MOP Lubień Południe)",
  "region": "zentral",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 535,
  "y": 401.8,
  "url": "https://www.google.com/maps/search/?api=1&query=Circle-K%20A1%20(MOP%20Lubie%C5%84%20Po%C5%82udnie)%20Lubie%C5%84%20Kujawski%20%20Polska",
  "meta": "Lubień Kujawski (A1) · Saisonal",
  "blurb": "MOP mit Ver-/Entsorgung in Lubień Kujawski (A1). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "circle-k-a1-mop-machnacz-po-noc-lubien-kujawski",
  "name": "Circle-K A1 (MOP Machnacz Północ)",
  "region": "zentral",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 534.7,
  "y": 401.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Circle-K%20A1%20(MOP%20Machnacz%20P%C3%B3%C5%82noc)%20Lubie%C5%84%20Kujawski%20%20Polska",
  "meta": "Lubień Kujawski (A1) · Saisonal",
  "blurb": "MOP mit Ver-/Entsorgung in Lubień Kujawski (A1). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "resort-camp-lusowko-lusowko",
  "name": "Resort & Camp Lusówko",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 500.8,
  "y": 404.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Resort%20%26%20Camp%20Lus%C3%B3wko%20Lus%C3%B3wko%20Polska",
  "meta": "Lusówko · Ganzjährig",
  "blurb": "Stellplatz / Camping in Lusówko. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stacja-narciarska-ladek-zdroj-ladek-zdroj",
  "name": "Stacja Narciarska Lądek Zdrój",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 505.2,
  "y": 451.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Stacja%20Narciarska%20L%C4%85dek%20Zdr%C3%B3j%20L%C4%85dek-Zdr%C3%B3j%20Polska",
  "meta": "Lądek-Zdrój · Saisonal",
  "blurb": "Stellplatz / Camping in Lądek-Zdrój. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "zacisze-pl-agow-lubuski",
  "name": "ZACISZE.PL",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 481.9,
  "y": 407.7,
  "url": "https://www.google.com/maps/search/?api=1&query=ZACISZE.PL%20%C5%81ag%C3%B3w%20Lubuski%20Polska",
  "meta": "Łagów Lubuski · Saisonal",
  "blurb": "Stellplatz / Camping in Łagów Lubuski. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-na-wydmie-eba",
  "name": "Camping Na Wydmie",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 511,
  "y": 349.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20Na%20Wydmie%20%C5%81eba%20Polska",
  "meta": "Łeba · Saisonal",
  "blurb": "Stellplatz / Camping in Łeba. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "fly-resort-eba-eba",
  "name": "FLY Resort Łeba",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 511.2,
  "y": 349.4,
  "url": "https://www.google.com/maps/search/?api=1&query=FLY%20Resort%20%C5%81eba%20%C5%81eba%20Polska",
  "meta": "Łeba · Saisonal",
  "blurb": "Stellplatz / Camping in Łeba. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-ma-oszow-ma-oszow",
  "name": "MOP Małoszów",
  "region": "sueden",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 552.2,
  "y": 448.2,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Ma%C5%82osz%C3%B3w%20Ma%C5%82osz%C3%B3w%20%20Polska",
  "meta": "Małoszów (S7) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Małoszów (S7). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-wiatraki-marozek",
  "name": "Camper Park Wiatraki",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 549.8,
  "y": 374.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Wiatraki%20Mar%C3%B3zek%20%20Polska",
  "meta": "Marózek (Olsztynek) · Saisonal",
  "blurb": "Stellplatz / Camping in Marózek (Olsztynek). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-bies-camp-michniowiec",
  "name": "Camper park BIES-CAMP",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 586,
  "y": 469,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20park%20BIES-CAMP%20Michniowiec%20Polska",
  "meta": "Michniowiec · Saisonal",
  "blurb": "Stellplatz / Camping in Michniowiec. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-mieszkowo-po-udnie-mieszkowo",
  "name": "MOP Mieszkowo Południe",
  "region": "masuren",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 551.2,
  "y": 374,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Mieszkowo%20Po%C5%82udnie%20Mieszkowo%20%20Polska",
  "meta": "Mieszkowo (S7) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Mieszkowo (S7). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-mieszkowo-po-noc-mieszkowo",
  "name": "MOP Mieszkowo Północ",
  "region": "masuren",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 551.3,
  "y": 373.8,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Mieszkowo%20P%C3%B3%C5%82noc%20Mieszkowo%20%20Polska",
  "meta": "Mieszkowo (S7) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Mieszkowo (S7). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "marigold-mirowo",
  "name": "Marigold",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 494.6,
  "y": 375.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Marigold%20Mirowo%20Polska",
  "meta": "Mirowo · Saisonal",
  "blurb": "Stellplatz / Camping in Mirowo. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "jezioro-kosiakowo-miros-awiec",
  "name": "Jezioro Kosiakowo",
  "region": "norden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 492,
  "y": 383.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Jezioro%20Kosiakowo%20Miros%C5%82awiec%20Polska",
  "meta": "Mirosławiec · Saisonal",
  "blurb": "Camper-Servicepunkt in Mirosławiec. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-ab-miedzyrzec-podlaski",
  "name": "Camper Park AB",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 585.1,
  "y": 407.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20AB%20Mi%C4%99dzyrzec%20Podlaski%20Polska",
  "meta": "Międzyrzec Podlaski · Saisonal",
  "blurb": "Stellplatz / Camping in Międzyrzec Podlaski. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "maciejowka-camper-park-miedzywodzie",
  "name": "Maciejówka Camper Park",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 473.1,
  "y": 369.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Maciej%C3%B3wka%20Camper%20Park%20Mi%C4%99dzywodzie%20Polska",
  "meta": "Międzywodzie · Saisonal",
  "blurb": "Stellplatz / Camping in Międzywodzie. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-port-mrzezyno-mrzezyno",
  "name": "Camper Park Port Mrzeżyno",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 480.4,
  "y": 365.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Port%20Mrze%C5%BCyno%20Mrze%C5%BCyno%20Polska",
  "meta": "Mrzeżyno · Saisonal",
  "blurb": "Stellplatz / Camping in Mrzeżyno. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kuter-port-nieznanowice",
  "name": "Kuter Port",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 551.2,
  "y": 458,
  "url": "https://www.google.com/maps/search/?api=1&query=Kuter%20Port%20Nieznanowice%20Polska",
  "meta": "Nieznanowice · Saisonal",
  "blurb": "Stellplatz / Camping in Nieznanowice. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanowiska-dla-kamperow-nowe-miasto-nad-pilica",
  "name": "Stanowiska dla kamperów",
  "region": "zentral",
  "kat": "camping",
  "status": "sehenswert",
  "x": 555,
  "y": 417.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanowiska%20dla%20kamper%C3%B3w%20Nowe%20Miasto%20nad%20Pilic%C4%85%20Polska",
  "meta": "Nowe Miasto nad Pilicą · Saisonal",
  "blurb": "Stellplatz / Camping in Nowe Miasto nad Pilicą. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "pcw-widok-nowinka",
  "name": "PCW WIDOK",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 586.6,
  "y": 359.6,
  "url": "https://www.google.com/maps/search/?api=1&query=PCW%20WIDOK%20Nowinka%20%20Polska",
  "meta": "Nowinka (Jez. Wigry) · Saisonal",
  "blurb": "Stellplatz / Camping in Nowinka (Jez. Wigry). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-ma-a-holandia-nowy-dwor-gdanski",
  "name": "MOP Mała Holandia",
  "region": "norden",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 533,
  "y": 360.3,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Ma%C5%82a%20Holandia%20Nowy%20Dw%C3%B3r%20Gda%C5%84ski%20%20Polska",
  "meta": "Nowy Dwór Gdański (S7) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Nowy Dwór Gdański (S7). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "nysa-jezioro-nysa",
  "name": "Nysa Jezioro",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 510.6,
  "y": 448.2,
  "url": "https://www.google.com/maps/search/?api=1&query=Nysa%20Jezioro%20Nysa%20%20Polska",
  "meta": "Nysa (Skorochów) · Ganzjährig",
  "blurb": "Stellplatz / Camping in Nysa (Skorochów). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osrodek-wczasowy-okoniny-nadjeziorne",
  "name": "Ośrodek Wczasowy",
  "region": "norden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 522.2,
  "y": 374.1,
  "url": "https://www.google.com/maps/search/?api=1&query=O%C5%9Brodek%20Wczasowy%20Okoniny%20Nadjeziorne%20Polska",
  "meta": "Okoniny Nadjeziorne · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Okoniny Nadjeziorne. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osrodek-lesna-przystan-osiek-grodkowski",
  "name": "Ośrodek Leśna Przystań",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 512.8,
  "y": 443.9,
  "url": "https://www.google.com/maps/search/?api=1&query=O%C5%9Brodek%20Le%C5%9Bna%20Przysta%C5%84%20Osiek%20Grodkowski%20Polska",
  "meta": "Osiek Grodkowski · Saisonal",
  "blurb": "Stellplatz / Camping in Osiek Grodkowski. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camp-jezioro-srebrne-osowiec",
  "name": "Camp Jezioro Srebrne",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 582.2,
  "y": 373.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Camp%20Jezioro%20Srebrne%20Osowiec%20Polska",
  "meta": "Osowiec · Saisonal",
  "blurb": "Stellplatz / Camping in Osowiec. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stacja-bp-ozarow-ozarow-mazowiecki",
  "name": "Stacja BP Ożarów",
  "region": "zentral",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 557.8,
  "y": 404.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Stacja%20BP%20O%C5%BCar%C3%B3w%20O%C5%BCar%C3%B3w%20Mazowiecki%20Polska",
  "meta": "Ożarów Mazowiecki · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Ożarów Mazowiecki. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kopalnia-camper-park-paniowice",
  "name": "Kopalnia Camper Park",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 504.1,
  "y": 431.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Kopalnia%20Camper%20Park%20Paniowice%20Polska",
  "meta": "Paniowice · Ganzjährig",
  "blurb": "Stellplatz / Camping in Paniowice. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kemping-w-parteczynach-parteczyny",
  "name": "Kemping w Partęczynach",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 539.5,
  "y": 375,
  "url": "https://www.google.com/maps/search/?api=1&query=Kemping%20w%20Part%C4%99czynach%20Part%C4%99czyny%20Polska",
  "meta": "Partęczyny · Saisonal",
  "blurb": "Stellplatz / Camping in Partęczyny. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kemping-polesie-pieszowola",
  "name": "Kemping Polesie",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 589.9,
  "y": 419.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Kemping%20Polesie%20Pieszowola%20Polska",
  "meta": "Pieszowola · Saisonal",
  "blurb": "Stellplatz / Camping in Pieszowola. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-na-miedzy-piwniczna-zdroj",
  "name": "Camping na miedzy",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 558.6,
  "y": 468,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20na%20miedzy%20Piwniczna-Zdr%C3%B3j%20Polska",
  "meta": "Piwniczna-Zdrój · Saisonal",
  "blurb": "Stellplatz / Camping in Piwniczna-Zdrój. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "pniewskie-przeds-komunalne-pniewy",
  "name": "Pniewskie Przeds. Komunalne",
  "region": "westen",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 494.9,
  "y": 402.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Pniewskie%20Przeds.%20Komunalne%20Pniewy%20Polska",
  "meta": "Pniewy · Saisonal",
  "blurb": "Camper-Servicepunkt in Pniewy. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "7-zab-pobierowo",
  "name": "7 żab",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 473.8,
  "y": 369.7,
  "url": "https://www.google.com/maps/search/?api=1&query=7%20%C5%BCab%20Pobierowo%20Polska",
  "meta": "Pobierowo · Saisonal",
  "blurb": "Stellplatz / Camping in Pobierowo. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "slowmood-camper-park-podgorzyn",
  "name": "Slowmood Camper Park",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 488.3,
  "y": 442.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Slowmood%20Camper%20Park%20Podg%C3%B3rzyn%20Polska",
  "meta": "Podgórzyn · Ganzjährig",
  "blurb": "Stellplatz / Camping in Podgórzyn. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osada-zborow-camp-bed-podlesice",
  "name": "Osada Zborów Camp & Bed",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 541.7,
  "y": 443.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Osada%20Zbor%C3%B3w%20Camp%20%26%20Bed%20Podlesice%20Polska",
  "meta": "Podlesice · Saisonal",
  "blurb": "Stellplatz / Camping in Podlesice. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "eko-marina-polanczyk-polanczyk",
  "name": "Eko Marina Polańczyk",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 582.1,
  "y": 467,
  "url": "https://www.google.com/maps/search/?api=1&query=Eko%20Marina%20Pola%C5%84czyk%20Pola%C5%84czyk%20%20Polska",
  "meta": "Polańczyk (Solina) · Saisonal",
  "blurb": "Stellplatz / Camping in Polańczyk (Solina). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "przystan-carynska-polanczyk",
  "name": "Przystań Caryńska",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 582.4,
  "y": 467,
  "url": "https://www.google.com/maps/search/?api=1&query=Przysta%C5%84%20Cary%C5%84ska%20Pola%C5%84czyk%20%20Polska",
  "meta": "Polańczyk (Solina) · Saisonal",
  "blurb": "Stellplatz / Camping in Polańczyk (Solina). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-pomiechowo-pomiechowo",
  "name": "Camper Park Pomiechowo",
  "region": "zentral",
  "kat": "camping",
  "status": "sehenswert",
  "x": 556.4,
  "y": 398.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Pomiechowo%20Pomiechowo%20Polska",
  "meta": "Pomiechowo · Ganzjährig",
  "blurb": "Stellplatz / Camping in Pomiechowo. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-popowo-wschod-s3-popowo",
  "name": "MOP Popowo Wschód S3",
  "region": "westen",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 481.8,
  "y": 403.8,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Popowo%20Wsch%C3%B3d%20S3%20Popowo%20%20Polska",
  "meta": "Popowo (S3) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Popowo (S3). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-popowo-zachod-s3-popowo",
  "name": "MOP Popowo Zachód S3",
  "region": "westen",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 481.9,
  "y": 403.6,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Popowo%20Zach%C3%B3d%20S3%20Popowo%20%20Polska",
  "meta": "Popowo (S3) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Popowo (S3). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "shell-mop-czerlejno-poznan",
  "name": "Shell, MOP Czerlejno",
  "region": "westen",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 508,
  "y": 405.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Shell%20MOP%20Czerlejno%20Pozna%C5%84%20%20Polska",
  "meta": "Poznań (S5 Nord) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Poznań (S5 Nord). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "shell-mop-dopiewo-poznan",
  "name": "Shell, MOP Dopiewo",
  "region": "westen",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 502.6,
  "y": 405.8,
  "url": "https://www.google.com/maps/search/?api=1&query=Shell%20MOP%20Dopiewo%20Pozna%C5%84%20%20Polska",
  "meta": "Poznań (S11 Süd) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Poznań (S11 Süd). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "shell-mop-siekierki-poznan",
  "name": "Shell, MOP Siekierki",
  "region": "westen",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 504.6,
  "y": 406.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Shell%20MOP%20Siekierki%20Pozna%C5%84%20%20Polska",
  "meta": "Poznań (S5 Süd) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Poznań (S5 Süd). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "olandia-camper-park-prusim",
  "name": "Olandia Camper Park",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 495.5,
  "y": 400.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Olandia%20Camper%20Park%20Prusim%20Polska",
  "meta": "Prusim · Saisonal",
  "blurb": "Stellplatz / Camping in Prusim. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "posir-przybrodzin-przybrodzin",
  "name": "POSiR Przybrodzin",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 517.6,
  "y": 402.7,
  "url": "https://www.google.com/maps/search/?api=1&query=POSiR%20Przybrodzin%20Przybrodzin%20Polska",
  "meta": "Przybrodzin · Saisonal",
  "blurb": "Stellplatz / Camping in Przybrodzin. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-nr-20-ma-a-szwajcaria-przywidz",
  "name": "Camping nr 20 Mała Szwajcaria",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 522,
  "y": 360.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20nr%2020%20Ma%C5%82a%20Szwajcaria%20Przywidz%20Polska",
  "meta": "Przywidz · Saisonal",
  "blurb": "Stellplatz / Camping in Przywidz. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "port-jachtowy-puck-puck",
  "name": "Port jachtowy Puck",
  "region": "norden",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 522.9,
  "y": 349.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Port%20jachtowy%20Puck%20Puck%20Polska",
  "meta": "Puck · Saisonal",
  "blurb": "MOP mit Ver-/Entsorgung in Puck. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-zamek-pu-tusk-pu-tusk",
  "name": "Camper Park Zamek Pułtusk",
  "region": "zentral",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 561.2,
  "y": 392.8,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Zamek%20Pu%C5%82tusk%20Pu%C5%82tusk%20Polska",
  "meta": "Pułtusk · Saisonal",
  "blurb": "Camper-Servicepunkt in Pułtusk. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanowisko-obs-ugi-kamperow-pyzdry",
  "name": "Stanowisko obsługi kamperów",
  "region": "westen",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 514.9,
  "y": 408.7,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanowisko%20obs%C5%82ugi%20kamper%C3%B3w%20Pyzdry%20Polska",
  "meta": "Pyzdry · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Pyzdry. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "gory-sto-owe-camp-radkow",
  "name": "Góry Stołowe Camp",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 498.5,
  "y": 448.5,
  "url": "https://www.google.com/maps/search/?api=1&query=G%C3%B3ry%20Sto%C5%82owe%20Camp%20Radk%C3%B3w%20Polska",
  "meta": "Radków · Saisonal",
  "blurb": "Stellplatz / Camping in Radków. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "riviera-camp-rad-ow",
  "name": "Riviera Camp",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 560,
  "y": 452,
  "url": "https://www.google.com/maps/search/?api=1&query=Riviera%20Camp%20Rad%C5%82%C3%B3w%20%20Polska",
  "meta": "Radłów (k. Tarnów) · Saisonal",
  "blurb": "Stellplatz / Camping in Radłów (k. Tarnów). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kotwica-rewa-rewa",
  "name": "Kotwica Rewa",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 524.2,
  "y": 351.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Kotwica%20Rewa%20Rewa%20Polska",
  "meta": "Rewa · Saisonal",
  "blurb": "Stellplatz / Camping in Rewa. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "seacamp-pl-rogowo",
  "name": "SeaCamp.pl",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 481.3,
  "y": 367,
  "url": "https://www.google.com/maps/search/?api=1&query=SeaCamp.pl%20Rogowo%20Polska",
  "meta": "Rogowo · Saisonal",
  "blurb": "Stellplatz / Camping in Rogowo. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kemping-nad-zalewem-brodzkim-ruda",
  "name": "Kemping nad Zalewem Brodzkim",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 551.7,
  "y": 431.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Kemping%20nad%20Zalewem%20Brodzkim%20Ruda%20Polska",
  "meta": "Ruda · Saisonal",
  "blurb": "Stellplatz / Camping in Ruda. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "hype-camper-rumunki-skepskie",
  "name": "Hype Camper",
  "region": "zentral",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 537.2,
  "y": 391.2,
  "url": "https://www.google.com/maps/search/?api=1&query=Hype%20Camper%20Rumunki%20Sk%C4%99pskie%20Polska",
  "meta": "Rumunki Skępskie · Saisonal",
  "blurb": "Camper-Servicepunkt in Rumunki Skępskie. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "miedzy-mostami-rybina",
  "name": "Między Mostami",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 534.1,
  "y": 358.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Mi%C4%99dzy%20Mostami%20Rybina%20Polska",
  "meta": "Rybina · Saisonal",
  "blurb": "Stellplatz / Camping in Rybina. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camp-fish-rybnik",
  "name": "Camp Fish",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 528.2,
  "y": 455.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Camp%20Fish%20Rybnik%20Polska",
  "meta": "Rybnik · Saisonal",
  "blurb": "Stellplatz / Camping in Rybnik. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "tropik-sarbinowo-sarbinowo",
  "name": "Tropik Sarbinowo",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 488.7,
  "y": 363.2,
  "url": "https://www.google.com/maps/search/?api=1&query=Tropik%20Sarbinowo%20Sarbinowo%20Polska",
  "meta": "Sarbinowo · Saisonal",
  "blurb": "Stellplatz / Camping in Sarbinowo. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "soul-camp-nowecin-sarbsko",
  "name": "Soul Camp Nowęcin",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 511.7,
  "y": 349.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Soul%20Camp%20Now%C4%99cin%20Sarbsko%20Polska",
  "meta": "Sarbsko · Saisonal",
  "blurb": "Stellplatz / Camping in Sarbsko. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osir-sierakow-sierakow",
  "name": "OSIR Sieraków",
  "region": "westen",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 492.5,
  "y": 399.2,
  "url": "https://www.google.com/maps/search/?api=1&query=OSIR%20Sierak%C3%B3w%20Sierak%C3%B3w%20Polska",
  "meta": "Sieraków · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Sieraków. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "jura-camp-siamoszyce-siamoszyce",
  "name": "Jura Camp Siamoszyce",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 541.8,
  "y": 443.8,
  "url": "https://www.google.com/maps/search/?api=1&query=Jura%20Camp%20Siamoszyce%20Siamoszyce%20Polska",
  "meta": "Siamoszyce · Saisonal",
  "blurb": "Stellplatz / Camping in Siamoszyce. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "przystanek-zapotocze-s-opnice",
  "name": "Przystanek Zapotocze",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 552.7,
  "y": 462.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Przystanek%20Zapotocze%20S%C5%82opnice%20Polska",
  "meta": "Słopnice · Ganzjährig",
  "blurb": "Stellplatz / Camping in Słopnice. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "wilcza-jama-smolnik",
  "name": "Wilcza Jama",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 584.7,
  "y": 470.2,
  "url": "https://www.google.com/maps/search/?api=1&query=Wilcza%20Jama%20Smolnik%20Polska",
  "meta": "Smolnik · Saisonal",
  "blurb": "Camper-Servicepunkt in Smolnik. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-jawor-nr-248-solina",
  "name": "Camping Jawor nr 248",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 582.5,
  "y": 467.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20Jawor%20nr%20248%20Solina%20Polska",
  "meta": "Solina · Saisonal",
  "blurb": "Stellplatz / Camping in Solina. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 }
];
