/* Polen-Camper: Stellplätze, Servicepunkte, Campingplätze & MOPs.
   Automatisch generiert aus Justines Camper-Liste. Kategorien: camping/camperservice/entsorgung. */
window.POLEN_CAMPER = [
 {
  "id": "camper-park-gzub-annopole",
  "name": "Camper Park Gzub",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 509.2,
  "y": 407.8,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Gzub%20Annopole%20%20Polska",
  "meta": "Annopole (Środa Wlkp.) · Ganzjährig",
  "blurb": "Stellplatz / Camping in Annopole (Środa Wlkp.). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "flaj-camper-serwis-augustow",
  "name": "FLAJ Camper Serwis",
  "region": "masuren",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 586.4,
  "y": 364.5,
  "url": "https://www.google.com/maps/search/?api=1&query=FLAJ%20Camper%20Serwis%20August%C3%B3w%20Polska",
  "meta": "Augustów · Saisonal",
  "blurb": "Camper-Servicepunkt in Augustów. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "jura-park-ba-tow-ba-tow",
  "name": "Jura Park Bałtów",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 569,
  "y": 433.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Jura%20Park%20Ba%C5%82t%C3%B3w%20Ba%C5%82t%C3%B3w%20Polska",
  "meta": "Bałtów · Ganzjährig",
  "blurb": "Stellplatz / Camping in Bałtów. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanowiska-obs-ugi-kamperow-bartoszyce",
  "name": "Stanowiska obsługi kamperów",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 556.3,
  "y": 357.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanowiska%20obs%C5%82ugi%20kamper%C3%B3w%20Bartoszyce%20Polska",
  "meta": "Bartoszyce · Saisonal",
  "blurb": "Stellplatz / Camping in Bartoszyce. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "estancia-camper-park-bia-a-gora",
  "name": "Estancia Camper Park",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 531.1,
  "y": 372.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Estancia%20Camper%20Park%20Bia%C5%82a%20G%C3%B3ra%20Polska",
  "meta": "Biała Góra · Saisonal",
  "blurb": "Stellplatz / Camping in Biała Góra. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanica-kajakarska-bia-ogard",
  "name": "Stanica kajakarska",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 490.1,
  "y": 368.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanica%20kajakarska%20Bia%C5%82ogard%20Polska",
  "meta": "Białogard · Saisonal",
  "blurb": "Stellplatz / Camping in Białogard. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "nadlesnictwo-choczewo-bia-ogora",
  "name": "Nadleśnictwo Choczewo",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 515.8,
  "y": 347.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Nadle%C5%9Bnictwo%20Choczewo%20Bia%C5%82og%C3%B3ra%20Polska",
  "meta": "Białogóra · Saisonal",
  "blurb": "Stellplatz / Camping in Białogóra. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osiw-dojlidy-bia-ystok",
  "name": "OSiW Dojlidy",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 589.5,
  "y": 380.6,
  "url": "https://www.google.com/maps/search/?api=1&query=OSiW%20Dojlidy%20Bia%C5%82ystok%20Polska",
  "meta": "Białystok · Saisonal",
  "blurb": "Stellplatz / Camping in Białystok. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "osir-bielawa-bielawa",
  "name": "OSiR Bielawa",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 501.3,
  "y": 443.9,
  "url": "https://www.google.com/maps/search/?api=1&query=OSiR%20Bielawa%20Bielawa%20Polska",
  "meta": "Bielawa · Saisonal",
  "blurb": "Stellplatz / Camping in Bielawa. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "bielsko-bia-a-camper-park-bielsko-bia-a",
  "name": "Bielsko-Biała Camper Park",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 535.4,
  "y": 461.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Bielsko-Bia%C5%82a%20Camper%20Park%20Bielsko-Bia%C5%82a%20Polska",
  "meta": "Bielsko-Biała · Ganzjährig",
  "blurb": "Stellplatz / Camping in Bielsko-Biała. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "pole-namiotowe-bobiecin",
  "name": "Pole namiotowe",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 500.5,
  "y": 364.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Pole%20namiotowe%20Bobi%C4%99cin%20Polska",
  "meta": "Bobięcin · Saisonal",
  "blurb": "Stellplatz / Camping in Bobięcin. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanowisko-obs-ugi-kamperow-boles-awiec",
  "name": "Stanowisko obsługi kamperów",
  "region": "westen",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 486.5,
  "y": 432,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanowisko%20obs%C5%82ugi%20kamper%C3%B3w%20Boles%C5%82awiec%20Polska",
  "meta": "Bolesławiec · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Bolesławiec. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kampery-borzechowo-borzechowo",
  "name": "Kampery Borzechowo",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 523.6,
  "y": 367.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Kampery%20Borzechowo%20Borzechowo%20Polska",
  "meta": "Borzechowo · Saisonal",
  "blurb": "Stellplatz / Camping in Borzechowo. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "jedwabno-camping-binduga-brajniki",
  "name": "Jedwabno Camping Binduga",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 556,
  "y": 373.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Jedwabno%20Camping%20Binduga%20Brajniki%20%20Polska",
  "meta": "Brajniki (Jez. Świętajno) · Saisonal",
  "blurb": "Stellplatz / Camping in Brajniki (Jez. Świętajno). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "tatrzanski-camper-park-bukowina-tatrzanska",
  "name": "Tatrzański Camper Park",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 550.3,
  "y": 471.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Tatrza%C5%84ski%20Camper%20Park%20Bukowina%20Tatrza%C5%84ska%20Polska",
  "meta": "Bukowina Tatrzańska · Ganzjährig",
  "blurb": "Stellplatz / Camping in Bukowina Tatrzańska. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-szczutki-po-udnie-bydgoszcz",
  "name": "MOP Szczutki Południe",
  "region": "norden",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 518.2,
  "y": 385.7,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Szczutki%20Po%C5%82udnie%20Bydgoszcz%20%20Polska",
  "meta": "Bydgoszcz (S5) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Bydgoszcz (S5). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-szczutki-po-noc-bydgoszcz",
  "name": "MOP Szczutki Północ",
  "region": "norden",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 518.3,
  "y": 385.4,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Szczutki%20P%C3%B3%C5%82noc%20Bydgoszcz%20%20Polska",
  "meta": "Bydgoszcz (S5) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Bydgoszcz (S5). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "inter-nos-kemping-na-wyspie-b-edno",
  "name": "Inter Nos – kemping na wyspie",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 490.1,
  "y": 405.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Inter%20Nos%20%20kemping%20na%20wyspie%20B%C5%82%C4%99dno%20Polska",
  "meta": "Błędno · Saisonal",
  "blurb": "Stellplatz / Camping in Błędno. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stacja-bp-celbowo",
  "name": "Stacja BP",
  "region": "norden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 522.8,
  "y": 350.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Stacja%20BP%20Celbowo%20%20Polska",
  "meta": "Celbowo (k. Puck) · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Celbowo (k. Puck). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-alexa-ch-apowo",
  "name": "Camping Alexa",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 522.4,
  "y": 347.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20Alexa%20Ch%C5%82apowo%20Polska",
  "meta": "Chłapowo · Ganzjährig",
  "blurb": "Stellplatz / Camping in Chłapowo. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "horyzont-camp-ch-apowo",
  "name": "Horyzont Camp",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 522.7,
  "y": 347.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Horyzont%20Camp%20Ch%C5%82apowo%20Polska",
  "meta": "Chłapowo · Ganzjährig",
  "blurb": "Stellplatz / Camping in Chłapowo. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-pa-ac-nad-jeziorem-chociwel",
  "name": "Camper Park Pałac Nad Jeziorem",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 481.7,
  "y": 381.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Pa%C5%82ac%20Nad%20Jeziorem%20Chociwel%20Polska",
  "meta": "Chociwel · Saisonal",
  "blurb": "Stellplatz / Camping in Chociwel. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "zatoka-zab-ockich-chomiaza-ksieza",
  "name": "Zatoka Zabłockich",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 516,
  "y": 394.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Zatoka%20Zab%C5%82ockich%20Chomi%C4%85%C5%BCa%20Ksi%C4%99%C5%BCa%20Polska",
  "meta": "Chomiąża Księża · Saisonal",
  "blurb": "Stellplatz / Camping in Chomiąża Księża. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-nr-80-cz-uchow",
  "name": "Camping nr 80",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 509.3,
  "y": 374.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20nr%2080%20Cz%C5%82uch%C3%B3w%20Polska",
  "meta": "Człuchów · Saisonal",
  "blurb": "Stellplatz / Camping in Człuchów. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "samoobs-ugowy-parking-przy-plazy-dar-owko-wschodnie",
  "name": "Samoobsługowy parking przy plaży",
  "region": "norden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 495.6,
  "y": 358.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Samoobs%C5%82ugowy%20parking%20przy%20pla%C5%BCy%20Dar%C5%82%C3%B3wko%20Wschodnie%20Polska",
  "meta": "Darłówko Wschodnie · Saisonal",
  "blurb": "Camper-Servicepunkt in Darłówko Wschodnie. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "sta-y-lad-dar-owko-zachodnie",
  "name": "Stały Ląd",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 494.9,
  "y": 358.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Sta%C5%82y%20L%C4%85d%20Dar%C5%82%C3%B3wko%20Zachodnie%20Polska",
  "meta": "Darłówko Zachodnie · Ganzjährig",
  "blurb": "Stellplatz / Camping in Darłówko Zachodnie. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "drohiczyn-camper-stop-drohiczyn",
  "name": "Drohiczyn Camper Stop",
  "region": "masuren",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 583.1,
  "y": 397.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Drohiczyn%20Camper%20Stop%20Drohiczyn%20Polska",
  "meta": "Drohiczyn · Saisonal",
  "blurb": "Camper-Servicepunkt in Drohiczyn. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-herbergerowka-duszniki-zdroj",
  "name": "Camper Park Herbergerówka",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 498.3,
  "y": 450.8,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20Herberger%C3%B3wka%20Duszniki-Zdr%C3%B3j%20Polska",
  "meta": "Duszniki-Zdrój · Saisonal",
  "blurb": "Stellplatz / Camping in Duszniki-Zdrój. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "na-wydmie-apartments-camp-dziwnowek",
  "name": "Na Wydmie Apartments & Camp",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 473.5,
  "y": 369.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Na%20Wydmie%20Apartments%20%26%20Camp%20Dziwn%C3%B3wek%20Polska",
  "meta": "Dziwnówek · Ganzjährig",
  "blurb": "Stellplatz / Camping in Dziwnówek. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-black-pearl-dziwnow",
  "name": "Camping Black Pearl",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 473.1,
  "y": 369.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20Black%20Pearl%20Dziwn%C3%B3w%20Polska",
  "meta": "Dziwnów · Saisonal",
  "blurb": "Stellplatz / Camping in Dziwnów. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "stanowisko-obs-ugi-kamperow-folusz",
  "name": "Stanowisko obsługi kamperów",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 569.3,
  "y": 462.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Stanowisko%20obs%C5%82ugi%20kamper%C3%B3w%20Folusz%20%20Polska",
  "meta": "Folusz (Jasło) · Saisonal",
  "blurb": "Camper-Servicepunkt in Folusz (Jasło). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "green-velo-camp-gawrych-ruda",
  "name": "Green Velo Camp",
  "region": "masuren",
  "kat": "camping",
  "status": "sehenswert",
  "x": 586.6,
  "y": 360.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Green%20Velo%20Camp%20Gawrych-Ruda%20Polska",
  "meta": "Gawrych-Ruda · Saisonal",
  "blurb": "Stellplatz / Camping in Gawrych-Ruda. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "mop-giebu-tow-giebu-tow",
  "name": "MOP Giebułtów",
  "region": "sueden",
  "kat": "entsorgung",
  "status": "sehenswert",
  "x": 546.9,
  "y": 452.6,
  "url": "https://www.google.com/maps/search/?api=1&query=MOP%20Giebu%C5%82t%C3%B3w%20Giebu%C5%82t%C3%B3w%20%20Polska",
  "meta": "Giebułtów (S7) · Ganzjährig",
  "blurb": "MOP mit Ver-/Entsorgung in Giebułtów (S7). Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kemping-stawy-marcowe-g-uszyca",
  "name": "Kemping Stawy Marcowe",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 497.8,
  "y": 444.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Kemping%20Stawy%20Marcowe%20G%C5%82uszyca%20Polska",
  "meta": "Głuszyca · Saisonal",
  "blurb": "Stellplatz / Camping in Głuszyca. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "parking-miejski-ladestation-gocza-kowice-zdroj",
  "name": "Parking miejski (Ladestation)",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 534,
  "y": 458.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Parking%20miejski%20(Ladestation)%20Gocza%C5%82kowice-Zdr%C3%B3j%20Polska",
  "meta": "Goczałkowice-Zdrój · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Goczałkowice-Zdrój. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "gotis-go-uchow",
  "name": "GOTiS",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 518.5,
  "y": 415.5,
  "url": "https://www.google.com/maps/search/?api=1&query=GOTiS%20Go%C5%82uch%C3%B3w%20Polska",
  "meta": "Gołuchów · Saisonal",
  "blurb": "Stellplatz / Camping in Gołuchów. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "bajka-hotel-resort-grodziec",
  "name": "Bajka Hotel & Resort",
  "region": "westen",
  "kat": "camping",
  "status": "sehenswert",
  "x": 519.4,
  "y": 414.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Bajka%20Hotel%20%26%20Resort%20Grodziec%20Polska",
  "meta": "Grodziec · Saisonal",
  "blurb": "Stellplatz / Camping in Grodziec. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "kaszuby-camper-stop-grzybno",
  "name": "Kaszuby Camper Stop",
  "region": "norden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 518.9,
  "y": 359.4,
  "url": "https://www.google.com/maps/search/?api=1&query=Kaszuby%20Camper%20Stop%20Grzybno%20%20Polska",
  "meta": "Grzybno (k. Kartuzy) · Saisonal",
  "blurb": "Camper-Servicepunkt in Grzybno (k. Kartuzy). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "lubie-resort-camper-park-gudowo",
  "name": "Lubie Resort Camper Park",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 488.6,
  "y": 379.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Lubie%20Resort%20Camper%20Park%20Gudowo%20Polska",
  "meta": "Gudowo · Saisonal",
  "blurb": "Stellplatz / Camping in Gudowo. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "winnica-sandomierska-camp-gory-wysokie",
  "name": "Winnica Sandomierska Camp",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 571.5,
  "y": 437.9,
  "url": "https://www.google.com/maps/search/?api=1&query=Winnica%20Sandomierska%20Camp%20G%C3%B3ry%20Wysokie%20Polska",
  "meta": "Góry Wysokie · Saisonal",
  "blurb": "Stellplatz / Camping in Góry Wysokie. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camping-kalina-nr-178-jantar",
  "name": "Camping Kalina nr 178",
  "region": "norden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 532.7,
  "y": 357.6,
  "url": "https://www.google.com/maps/search/?api=1&query=Camping%20Kalina%20nr%20178%20Jantar%20Polska",
  "meta": "Jantar · Saisonal",
  "blurb": "Stellplatz / Camping in Jantar. Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "parking-jasnej-gory-czestochowa",
  "name": "Parking Jasnej Góry",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 535.4,
  "y": 438.3,
  "url": "https://www.google.com/maps/search/?api=1&query=Parking%20Jasnej%20G%C3%B3ry%20Cz%C4%99stochowa%20%20Polska",
  "meta": "Częstochowa (Jasna Góra) · Saisonal",
  "blurb": "Camper-Servicepunkt in Częstochowa (Jasna Góra). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "camper-park-nad-sosina-jaworzno",
  "name": "Camper Park nad Sosiną",
  "region": "sueden",
  "kat": "camperservice",
  "status": "sehenswert",
  "x": 538.2,
  "y": 452.1,
  "url": "https://www.google.com/maps/search/?api=1&query=Camper%20Park%20nad%20Sosin%C4%85%20Jaworzno%20Polska",
  "meta": "Jaworzno · Ganzjährig",
  "blurb": "Camper-Servicepunkt in Jaworzno. Ganzjährig geöffnet. Genaue Lage & Details über Google Maps."
 },
 {
  "id": "hotel-camping-jazy-jazy",
  "name": "Hotel Camping Jazy",
  "region": "sueden",
  "kat": "camping",
  "status": "sehenswert",
  "x": 544.2,
  "y": 462.5,
  "url": "https://www.google.com/maps/search/?api=1&query=Hotel%20Camping%20Jazy%20Jazy%20%20Polska",
  "meta": "Jazy (Maków Podh.) · Saisonal",
  "blurb": "Stellplatz / Camping in Jazy (Maków Podh.). Saisonal geöffnet. Genaue Lage & Details über Google Maps."
 }
];
